spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    name: stackssh-server
  profiles:
    active: dev
