CREATE TABLE IF NOT EXISTS `chat_session_state` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` varchar(64) NOT NULL COMMENT '会话ID',
  `user_id` varchar(64) NOT NULL COMMENT '用户ID',
  `agent_id` varchar(64) NOT NULL COMMENT '智能体ID',
  `task_summary` varchar(500) DEFAULT NULL COMMENT '任务摘要',
  `current_intent` varchar(100) DEFAULT NULL COMMENT '当前意图',
  `intent_summary` text COMMENT '意图摘要历史',
  `tool_summary` text COMMENT '工具执行摘要',
  `last_user_message_digest` varchar(64) DEFAULT NULL COMMENT '最近一次用户消息摘要指纹',
  `cached_search_context` longtext COMMENT '缓存的搜索增强上下文(JSON)',
  `cached_rag_chunks` longtext COMMENT '缓存的知识库片段(JSON)',
  `last_terminal_session_id` varchar(64) DEFAULT NULL COMMENT '最近绑定的终端会话ID',
  `turn_count` int NOT NULL DEFAULT '0' COMMENT '轮次计数',
  `context_version` int NOT NULL DEFAULT '1' COMMENT '上下文版本',
  `last_round_at` bigint DEFAULT NULL COMMENT '最近一轮完成时间戳',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_id` (`session_id`),
  KEY `idx_user_agent` (`user_id`,`agent_id`),
  KEY `idx_last_round_at` (`last_round_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会话上下文状态';
